apiVersion: v1
kind: Namespace
metadata:
  name: argoci-workflows
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: argoci
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress
spec:
  finalizers:
  - kubernetes
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    path: stable/nginx-ingress
    repoURL: https://github.com/helm/charts
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd
    repoURL: https://github.com/argoproj/argoproj-deployments
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoci
spec:
  destination:
    namespace: argoci
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argoci
    repoURL: https://github.com/argoproj/argoproj-deployments
    targetRevision: HEAD
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: default
  source:
    path: stable/cert-manager
    repoURL: https://github.com/helm/charts
    targetRevision: a52c24dfa5e9b8dbdc5ff5092a6fef864792cfeb
