# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: tensorflow/tensorflow:1.7.0
    working_directory: /aiops
    steps:
      - checkout
      - run:
          name: Copy model.py
          command: |
            cp /aiops/mnist/model.py /opt/model.py
            chmod +x /opt/model.py
      - run:
          name: Run model.py
          command: |
           /usr/bin/python /aiops/mnist/model.py
           
      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      # - run:
      #     name: run tests
      #     command: |
      #       . venv/bin/activate
      #       python manage.py test

      # - store_artifacts:
      #     path: test-reports
      #     destination: test-reports