#This container contains your model and any helper scripts specific to your model.
FROM tensorflow/tensorflow:1.7.0

ADD requirements-test.txt /opt/requirements-test.txt
RUN pip install -r /opt/requirements-test.txt

ADD mnist_client_test.py /opt/mnist_client_test.py
ADD mnist_client.py /opt/mnist_client.py
ADD test_helper.py /opt/test_helper.py

RUN chmod +x /opt/mnist_client_test.py
RUN chmod +x /opt/mnist_client.py
RUN chmod +x /opt/test_helper.py

ENTRYPOINT ["/usr/bin/python"]
CMD ["/opt/mnist_client_test.py"]
