apiVersion: 0.3.0
environments:
  default:
    destination:
      namespace: mnist
      server: https://5D360233ABFB4F946FC6F22C40A09AF8.yl4.us-west-2.eks.amazonaws.com
    k8sVersion: v1.11.8
    path: default
kind: ksonnet.io/app
libraries:
  kubeflow/tf-serving:
    name: tf-serving
    registry: kubeflow
    version: 797bcb7407a589bacc35b9624120f51f36a83468
name: mnist_ksonnet_app
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/v0.4.1/kubeflow
version: 0.0.1
