apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    path: stable/nginx-ingress
    repoURL: https://github.com/helm/charts
    targetRevision: HEAD
